#!/bin/bash

NORMALIZE_PROJECT_DIR="/home/caprioli/personal docs/project/normalize"

if [ -z "$1" ]; then
	echo -e "Usage:\n\t$0: <file to normalize.mp3>"
	exit -1
fi

if [ -z "`ls  /dev/shm/tmp 2> /dev/null | grep trash`" ]; then
	mkdir -p /dev/shm/tmp/trash/split
fi

cp "$1" "/dev/shm/tmp/trash/"

# ETT: DEBUG=si	# comment/decomment this to enable/disable DEBUG

if [ -n "$DEBUG" ]; then  # DEBUG
	echo "DEBUG pause"
	echo "[press a key to continue]"
	read lin
fi

echo "Split with audacity silence finder (-26 dB; 0,2; 0,00) and save to /dev/shm/tmp/trash/split/S-%d.mp3"
echo "(should include before first label named as S-0 and check no more 9999 pices"
echo "[press a key to continue (audacity will open automatically)]"

read lin

audacity /dev/shm/tmp/trash/"$1"

echo "Now you should have the splitted files into /dev/shm/tmp/trash/split"
echo "[press a key to continue]"
read lin

mv /dev/shm/tmp/trash/split/S.mp3 /dev/shm/tmp/trash/split/S-1.mp3

ls /dev/shm/tmp/trash/split > "/dev/shm/tmp/trash/lst"

if [ -n "$DEBUG" ]; then  # DEBUG
	echo "DEBUG pause"
	echo "[press a key to continue]"
	read lin
fi

cd /dev/shm/tmp/trash/split
"${NORMALIZE_PROJECT_DIR}"/rename > tmp.sh
sh tmp.sh
rm tmp.sh

if [ -n "$DEBUG" ]; then  # DEBUG
	echo "DEBUG pause"
	echo "[press a key to continue]"
	read lin
fi

if [ -z "`ls  /dev/shm/tmp/trash/ 2> /dev/null | grep mp3_norm`" ]; then
	mkdir -p /dev/shm/tmp/trash/mp3_norm
fi

for i in *; do
	# salva direttamente in /dev/shm/tmp/trash/mp3_norm
	"${NORMALIZE_PROJECT_DIR}"/normalize_ETT "$i"
done

if [ -n "$DEBUG" ]; then  # DEBUG
	echo "DEBUG pause"
	echo "[press a key to continue]"
	read lin
fi

cd /dev/shm/tmp/trash/mp3_norm/
cat * > ../"`echo $1| sed s/'.mp3'/'_norm'/`".mp3

echo "Resave with audacity to clean headers of cat of the files mp3"
echo "Import in audacity"
echo "[Press a key to end this script and open audacity and after delete all working file]"

read lin

audacity /dev/shm/tmp/trash/"`echo $1| sed s/'.mp3'/'_norm'/`".mp3

if [ -n "$DEBUG" ]; then  # DEBUG
	echo "DEBUG pause"
	echo "[press a key to continue before deletion]"
	read lin
fi

cp /dev/shm/tmp/trash/"`echo $1| sed s/'.mp3'/'_norm'/`".mp3 /dev/shm
rm -R /dev/shm/tmp/trash/
